---
Name: sabot_config
---
SiteTree:
  extensions:
    - SabotPageExtension
ContentController:
  extensions:
    - SabotControllerExtension
LeftAndMain:
  extra_requirements_javascript:
    - sabot/javascript/HTML_CodeSniffer/HTMLCS.js
    - sabot/javascript/HTML_CodeSniffer/HTMLCS.Util.js
    - sabot/javascript/sabot-htmlsniffer.js
  extra_requirements_css:
    - sabot/css/sabot-admin.css

---
Name: sabot_ms_config
Only:
  moduleexists: multisites
---
Site:
  extensions:
    - SabotConfigExtension
