---
Name: sabot_config
Only:
  moduleexists: multisites
---
Site:
  extensions:
    - SabotConfigExtension
SiteTree:
  extensions:
    - SabotPageExtension
ContentController:
  extensions:
    - SabotControllerExtension